apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exercise-db-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---      

apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: exercise-db
  template:
    metadata:
      labels:
        component: exercise-db
    spec:
      volumes:
        - name: exercise-db-storage
          persistentVolumeClaim:
            claimName: exercise-db-persistent-volume-claim
      containers:
        - name: exercise-db
          image: azsuth/beefy-gainz-exercise-db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: exercise-db-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-root-password
                  key: password
            - name: POSTGRES_DB
              value: exercise

---

apiVersion: v1
kind: Service
metadata:
  name: exercise-db-service
spec:
  type: ClusterIP
  selector:
    component: exercise-db
  ports:
    - port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      component: adminer
  template:
    metadata:
      labels:
        component: adminer
    spec:
      containers:
        - name: adminer
          image: adminer
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: adminer-service
spec:
  type: ClusterIP
  selector:
    component: adminer
  ports:
    - port: 8080
      targetPort: 8080